### ISSUE TITLE
Question : Is there a way to use spring rewrite recipe for a non spring boot based application ?

### ISSUE THREAD

**Issue by shivpatel1** [openrewrite/rewrite-spring#427]
## What version of OpenRewrite are you using?

I am using

- OpenRewrite v5.4.2
- Maven/Gradle plugin v3.8.1
- rewrite-_module_ v5.0.7

## How are you running OpenRewrite?

I am using the Maven plugin, and my project is a single module project.
```xml
<plugin>
						<groupId>org.openrewrite.maven</groupId>
						<artifactId>rewrite-maven-plugin</artifactId>
						<version>5.4.2</version>
						<configuration>
							<activeRecipes>
								<recipe>org.openrewrite.java.spring.security6.UpgradeSpringSecurity_6_0</recipe>
							</activeRecipes>
						</configuration>
						<dependencies>
							<dependency>
								<groupId>org.openrewrite.recipe</groupId>
								<artifactId>rewrite-spring</artifactId>
								<version>5.0.7</version>
								<scope>runtime</scope>
							</dependency>
						</dependencies>
					</plugin>
```

======

While using this plugin in a non spring boot based application (of course having spring framework and spring security configured inside), we were getting errors regarding ResourceLoader not found. And then the error got solved automatically but started getting another error like below.

Caused by: java.lang.NullPointerException: Cannot invoke "String.compareTo(String)" because the return value of "org.openrewrite.maven.tree.MavenMetadata$Snapshot.getTimestamp()" is null
	at org.openrewrite.maven.internal.MavenPomDownloader.maxSnapshot(MavenPomDownloader.java:428)
	at org.openrewrite.maven.internal.MavenPomDownloader.mergeMetadata(MavenPomDownloader.java:411)
	at org.openrewrite.maven.internal.MavenPomDownloader.downloadMetadata(MavenPomDownloader.java:282)
	

Then, based on this github page details, we came to know that this recipe is for spring-boot based projects. And we confirmed that it does make changes in spring-boot based application.

So, just wanted to know is there any way we can use this plugin and recipe for a non spring boot based applications as well?

**Comment by knutwannheden** [comment]
@shivpatel1 Thanks for your report. Actually, this particular recipe is not specific to Spring Boot and should also work for a regular Spring-based application.

For some reason it looks like you have a snapshot of a Maven artifact in your Maven repo, for which there is no timestamp. This is unusual. Possibly clearing your local Maven cache could help resolve the issue?

**Comment by shivpatel1** [comment]
@knutwannheden  : Thank you for such prompt response. Appreciated. 

We already cleaned up our local .m2 as a troubleshooting step. But could not overcome the error. And then we also looked for different configuration options provided by rewrite plugin. We configured skipMavenParsing by setting it to true and noticed that the error was not thrown then on. We could also see the INFO level log in console about "Running recipe(s)...". But that did not change any file in the project and it showed build success at the end. This project contains all XML based configurations for spring-oauth and spring-security.

Then only we looked up more and read a line on this github page and somehow interpreted that this is designed for spring boot only. And we tried with one spring-boot based app we have where it actually worked as expected.

Some additional information : For non-spring boot based application, we have a project with all spring dependencies configured in a parent project. So, here, we tried configuring rewrite plugin in child project directly as well as in the parent pom through maven profiling as suggested on docs.rewrite.org. But noticed the same behavior both the times.

**Comment by shivpatel1** [comment]
@knutwannheden  :  Based on the results of skipMavenParsing and your comments about snapshot, we checked further and realized that out of plenty of dependencies our project has, we have few snapshot based dependencies as well.
We removed them temporary and confirmed that the plugin execution goes further without any issue.

Thanks for pointing out.

But again, it did not make any changes in our XML based configurations. Does this plugin work on JAVA classes only ?

**Comment by knutwannheden** [comment]
@shivpatel1 I haven't read anything in the documentation regarding this, but it appears like snapshot versions sometimes don't have a timestamp attached to them. So in an attempt to fix this, I've pushed a commit which simply ignores any such snapshots. Shortly there should be a snapshot version available of `rewrite-maven` (with timestamp 😄 ). See [here](https://docs.openrewrite.org/reference/snapshot-instructions) for instructions on how to access OpenRewrite snapshot versions. You would have to configure the Maven plugin's dependency to use this snapshot version. Alternatively you can wait for the next patch release of OpenRewrite.

It would be great to hear if this fixes your issue.

**Comment by shivpatel1** [comment]
@knutwannheden  : Thank you very much for taking an action quickly.

But the main issue is still there. I have removed those snapshot dependencies completely from my project pom. So, they do not bother anymore. And the plugin execution proceeds as expected. But it is not making any changes in my XML file based beans configurations.  Please check below as an example of what we expect to be changed.

Below is some of the details extracted from our Spring XML configuration file.

<beans
        ...
        xmlns:oauth="http://www.springframework.org/schema/security/oauth2" 
	xmlns:sec="http://www.springframework.org/schema/security"
        xsi:schemaLocation="...
        ...
        http://www.springframework.org/schema/security
	http://www.springframework.org/schema/security/spring-security.xsd
	http://www.springframework.org/schema/security/oauth2 
	https://www.springframework.org/schema/security/spring-security-oauth2.xsd">

...
...
<sec:global-method-security pre-post-annotations="enabled" proxy-target-class="true">
		<sec:expression-handler ref="expHandler" />
	</sec:global-method-security>
...
...
</beans>
Now, while running the rewrite-security recipe for upgrading spring security 6, it internally executes spring security 5.8 upgrade. And as per https://docs.openrewrite.org/recipes/java/spring/security5/replaceglobalmethodsecuritywithmethodsecurityxml  documentation, it should have changed global-method-security to method-security. Which is not happening.

This is just one example from our configuration file. But the result is like the recipe is not making any single change in it.

**Comment by shivpatel1** [comment]
@knutwannheden  :  Just to provide an update for my above query.  The plugin works if we do not have aliases for XML namespace. Like,

If we have <global-method-security..... > in our xml file instead of <sec:global-method-security.... > then the recipe works as expected and changes it to <method-security .... >.

So, probably the recipe needs a little bit of an enhancement to consider the alias as well.  :)

**Comment by knutwannheden** [comment]
Thanks for the details. I will try to verify that the recipe handles the XML namespaces correctly.

**Comment by timtebeek** [comment]
This has since been fixed upstream; thanks again!
